version: '2.1'

services:
  myapp_db:
    image: "percona:latest"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: myapp_db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD', 'mysqladmin', '-uroot', '-ppass', 'ping', '-h', '127.0.0.1']
      timeout: 1s
      retries: 30

  myapp:
    image: "myapp:latest"
    entrypoint: /app/myapp --config=/config/config.txt
    volumes:
      - ./app/config:/config
    ports:
      - "8080:8080"
    depends_on:
      myapp_db:
        condition: service_healthy
