version: '2.1'

services:
  myapp_db:
    image: "percona:latest"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: myapp_db
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD', 'mysqladmin', '-uroot', '-ppass', 'ping', '-h', '127.0.0.1']
      timeout: 1s
      retries: 30

  vk_api:
    build: ./mock/
    volumes:
      - ../settings.py:/settings/settings.py
      - ../utils/paths.py:/settings/utils/paths.py
      - /tmp/myapp_tests_logs:/tmp
      - ./mock/flask_app:/app
    working_dir: /app
    entrypoint: ["python", "views.py"]
    ports:
      - "8008:8008"
    depends_on:
      myapp_db:
        condition: service_healthy

  myapp:
    image: "myapp:latest"
    entrypoint: /app/myapp --config=/config/config.txt
    volumes:
      - ./app/config:/config
    ports:
      - "8070:8070"
    depends_on:
      myapp_db:
        condition: service_healthy
      vk_api:
        condition: service_started